### ISSUE TITLE
follow directions not working

### ISSUE THREAD

**Issue by AD1CTV** [reveddit/reveddit#10]
ad1ctv@ad1:~$ git clone git@github.com:reveddit/reveddit.git && cd reveddit
Cloning into 'reveddit'...
The authenticity of host 'github.com (140.82.113.3)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? y
Please type 'yes', 'no' or the fingerprint: yes
Warning: Permanently added 'github.com,140.82.113.3' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ad1ctv@ad1:~$

**Comment by rhaksw** [comment]
You need to [set up your ssh keys](https://stackoverflow.com/questions/2643502/git-how-to-solve-permission-denied-publickey-error-when-using-git).
