### ISSUE TITLE
Approved posts showing as unapproved, using extension on Firefox

### ISSUE THREAD

**Issue by Regina3000** [reveddit/reveddit#13]
I'm using version 0.0.2.5 of the extension on Firefox. Posts that are approved, and which show up in the sub, have the "unapproved" box which reads:

"[Reveddit Real-Time] ([redacted] note
This post is unapproved. It is either waiting to be approved, or it was removed by someone or some robot. More details may appear in a message above from reddit. It is not currently visible in r/violinist and may not appear in web search results.

"[View the post on Reveddit.com] ([redacted])"

**Comment by rhaksw** [comment]
Hi, I'm unable to replicate your experience. Do you have an example link or screenshot showing the post's title and subreddit to share?

Note that if you submit a post that is removed by Reddit's spam filter, such as [this one](https://new.reddit.com/r/violinist/comments/1101iaq/this_came_extremely_fast_and_great_quality/), Reddit will not show a removal notice for anyone for the first 24 hours. Also, the submitter will still see it listed in the subreddit's new feed, and possibly the home page. More info on that [here](https://www.reveddit.com/about/faq/#reddit-does-not-say-post-removed).

**Comment by rhaksw** [comment]
Okay I see it now. It shows up on links to comments. This is a pretty big bug that's going to confuse a lot of people. Thank you for bringing it to my attention.
