### ISSUE TITLE
Reveddit mistakenly converts post IDs composed entirely out of digits to base36

### ISSUE THREAD

**Issue by untitlese5566** [reveddit/reveddit#14]
The issue appeared when I tried to take a look at the post https://www.reveddit.com/v/AmItheAsshole/comments/1007046/aita_for_assuming_a_couples_trip_meant_no_kids/
If you try yourself, you'll see after the post finishes loading that the title gets changed into "Companies Are Losing Easy Profits By Devoting Exceptional Resources to Alienating Hard-Won Customers".
The issue is not with Pushshift. Unddit works fine: https://www.unddit.com/r/AmItheAsshole/comments/1007046/aita_for_assuming_a_couples_trip_meant_no_kids/ and shows the post body and title correctly.
I think the issue is that Reveddit thinks the post id "1007046" is an int and converts it into base36 ("ll1i"). Reddit has a post with that id (https://old.reddit.com/r/reddit.com/comments/ll1i/companies_are_losing_easy_profits_by_devoting/) and it has the **exact** same title as what Reveddit replaced it with.

**Comment by rhaksw** [comment]
Fixed! Thank you for reporting this.

It's an issue with Pushshift's API that can be mitigated by the client. Pushshift's [documentation](https://api.pushshift.io/redoc#operation/search_reddit_posts_reddit_search_submission_get) says ID is a string, and that works unless the string is all digits. In that case it's interpreted as base 10 and gives an unexpected response,

- [?ids=11tcr62](https://api.pushshift.io/reddit/search/submission?ids=11tcr62&filter=id,title) returns `"id": "11tcr62"`
- [?ids=1007046](https://api.pushshift.io/reddit/search/submission?ids=1007046&filter=id,title) returns `"id": "ll1i"`

The solution for clients like Reveddit is to convert every lookup for submissions to base 10.
