### ISSUE TITLE
it is broken on Firefox

### ISSUE THREAD

**Issue by dtantono** [reveddit/reveddit#16]
Hi
I have this extension on Chrome and Firefox. The chrome looks okay. But, the firefox is broken and I already activated this parameter (https://github.com/reveddit/real-time-extension/issues/10#issuecomment-1396335417). What do you think?
![image](https://github.com/reveddit/reveddit/assets/29157187/25980074-2af0-4ca6-ba8a-2918e2fe8b37)
![image](https://github.com/reveddit/reveddit/assets/29157187/fd95e775-d9ed-427d-b261-58eb68bdc5c1)

**Comment by rhaksw** [comment]
See here: https://github.com/reveddit/real-time-extension/issues/10#issuecomment-1396335417

**Comment by dtantono** [comment]
@rhaksw I already did that and it does not worked. What do you think?

**Comment by rhaksw** [comment]
There are two issues. One is the error message that appeared was wrong. I just fixed that. The other is your tracking protection settings made it impossible for the site to fetch data from Reddit.  You need to disable tracking protection for Reveddit for it to work. More info on why can be found [here](https://www.reveddit.com/about/faq/#firefox).

On another note, I have three or four messages from you about this issue. One message is enough, and opening [#12](https://github.com/reveddit/real-time-extension/issues/12) and commenting on [#10](https://github.com/reveddit/real-time-extension/issues/10) in the other repo was not necessary to get my attention.

**Comment by dtantono** [comment]
@rhaksw I did that and it does not worked. What do you think?
![image](https://github.com/reveddit/reveddit/assets/29157187/1288aaf4-4a6f-49a6-858b-a599be6a5502)
![image](https://github.com/reveddit/reveddit/assets/29157187/63e33423-c653-4cb6-8ed6-e2e3f1afff27)

**Comment by rhaksw** [comment]
Read the whole message:

> If this does not resolve the issue, there may be a conflicting extension blocking connections to reddit from other websites.
