### ISSUE TITLE
PullPush - PushShift replacement

### ISSUE THREAD

**Issue by pullpush-io** [reveddit/reveddit#17]
Hello!

I created a replacement service for PushShift functionality that's now restricted. See https://pullpush.io/ for details. Overall it will aim to be compatible to Dec-2022 version of PushShift API.

In case you feel burned out by the whole 3rd party tool affair; I would like to ask for permission to fork and rebrand your project. Personally I found your project **indispensable** in cases where reddit moderators are not acting in good faith (crypto scams and shills in particular). 

PullPush Actual

**Comment by rhaksw** [comment]
Thanks, but permission is not required per the [license](https://github.com/reveddit/reveddit/blob/master/LICENSE).

If you're asking for my endorsement before you launch, you don't have it. And I'm not burned out, I'm just getting started.

**Comment by pullpush-io** [comment]
Thanks, it is a common courtesy to notify/ask. I will still submit upstream PRs unless you reject those purely on the basis of their origin. 

And I hope that in due time you will revisit the reasons for your decision (whatever they are). We should be working together not maintaining two separate projects.

**Comment by rhaksw** [comment]
What motivated you to do this work? How are you funding it?

My own project's costs are minimal, around $20 per month. But you're talking about ingesting all Reddit data in a much tougher environment. Reddit will not support your effort with its API, so whatever method you use to ingest will be more expensive. You will also be taking on all the egress costs that Pushshift had, which were substantial.

**Comment by pullpush-io** [comment]
Server costs are on the ballpark of 1k usd / mo. I can cover that from my own pocket. I think the biggest tip is not to use could services, then you have 0 egress costs.

**Comment by rhaksw** [comment]
And what motivates you to build this and spend $1k/mo?

**Comment by pullpush-io** [comment]
- To build? I need it anyway for data analytics.
- To make it public? Same thing as you. Plus I hate crypto scams. Also sticking the middle finger to wannabe-post-apocalyptic discount Elon Musk is as good motivation as any.

**Comment by rhaksw** [comment]
My only motivation is to let people know about shadow moderation. It sounds like we have different aims, though that doesn't necessarily need to be a problem.

I'll accept PRs on a branch called `hcs`, which would be shareable via https://hcs.reveddit.com. If that gets a userbase and everything still looks good I will merge them onto www.
