### ISSUE TITLE
[enhancement] Request for Backup API

### ISSUE THREAD

**Issue by Cosmicoppai** [reveddit/reveddit#8]
We've recently developed a scraper to scrape posts & comments from reddit, and storing it in the postgres when they're deleted from the reddit. Unlike Pushshift we don't re-delete posts after a few days.

* The suggestion here is to add this API as a backup to pushshift API.

Currently the scraper is only focused on 'r/cryptocurrency' but it can be easily scaled for other ones also.

The link to our API and some deleted posts which are available in our db:

https://uncensor.cc
https://uncensor.cc/api?f=p&sub=cryptocurrency&q=btc&ups=5&page=1
https://uncensor.cc/api?pid=r3iztf&page=1

**Comment by rhaksw** [comment]
Hi, thank you for sharing your work. I'm still waiting to see what will happen with Pushshift overwriting comments. So far there has been no announcement from the author about this. I checked out your API and noticed you use different field names from those used by reddit's API. That would make it harder to work with. Also I'm likely to only add another data source if it can work with all subreddits and if I can get to know its author. Thank you.
